name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  check:
    name: Check & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install Rust toolchain
        run: rustup toolchain install stable --profile minimal
      - name: Add Rust components
        run: rustup default stable
      - run: cargo check --workspace
      - run: cargo test --workspace
